const Database = require('better-sqlite3');
const path = require('path');
const fs = require('fs');

const dbPath = process.env.DB_PATH || path.join(__dirname, 'data', 'policies.db');
fs.mkdirSync(path.dirname(dbPath), { recursive: true });
const db = new Database(dbPath);

db.exec(`
  CREATE TABLE IF NOT EXISTS payers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    state TEXT,
    plan_type TEXT,
    conservative_weeks INTEGER,
    conservative_notes TEXT,
    reflux_duration_sec REAL,
    vessel_diameter_mm REAL,
    ultrasound_notes TEXT,
    ceap_required TEXT,
    documentation TEXT,
    cpt_codes TEXT,
    icd10_codes TEXT,
    preauth_required INTEGER DEFAULT 0,
    preauth_notes TEXT,
    gotchas TEXT,
    source_url TEXT,
    last_verified TEXT,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS policy_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    payer_id INTEGER NOT NULL,
    changed_field TEXT,
    old_value TEXT,
    new_value TEXT,
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (payer_id) REFERENCES payers(id) ON DELETE CASCADE
  );
`);

try { db.exec('CREATE UNIQUE INDEX IF NOT EXISTS idx_payer_name_state ON payers(name, state)'); } catch(e) {}

const ins = db.prepare(`INSERT OR IGNORE INTO payers
  (name, state, plan_type, conservative_weeks, conservative_notes, reflux_duration_sec, vessel_diameter_mm,
   ultrasound_notes, ceap_required, documentation, cpt_codes, icd10_codes, preauth_required, preauth_notes, gotchas, source_url, last_verified, notes)
  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);

const policies = [
  // BCBS variants
  ['Blue Cross Blue Shield', 'Illinois', 'Commercial',
   12, 'Minimum 12 weeks of conservative therapy with graduated compression stockings (20-30 mmHg or greater). Must be documented at each visit with compliance noted.',
   0.5, null,
   'Duplex ultrasound required showing venous reflux >0.5 seconds in great saphenous vein (GSV), small saphenous vein (SSV), or tributary veins. Must be performed by accredited vascular lab.',
   'C2 or higher (CEAP classification required)',
   'Office notes documenting symptoms (pain, heaviness, swelling, skin changes), compression stocking prescription and compliance documentation, duplex ultrasound report, photo documentation of varicosities',
   '36475, 36476, 36478, 36479, 36482, 36483, 93971',
   'I83.009, I83.019, I83.029, I83.209, I83.219, I83.229',
   1, 'Prior auth required for all thermal ablation procedures. Submit with duplex report and conservative therapy documentation.',
   'Stocking compliance must be documented at EVERY visit — single missed note can trigger denial. Stockings must be 20-30 mmHg minimum.',
   'https://www.bcbsil.com/provider/clinical/policies.html', '2025-01-01',
   'One of the stricter commercial payers. Conservative therapy documentation must be meticulous.'],

  ['Blue Cross Blue Shield', 'Texas', 'Commercial',
   12, '12 weeks conservative therapy with compression stockings 20-30 mmHg. Physician must document patient compliance at each visit.',
   0.5, null,
   'Duplex ultrasound demonstrating reflux >0.5 sec in target vessel. Must be performed within 6 months of planned procedure.',
   'C2 or higher',
   'Clinical notes with symptom documentation, compression stocking Rx and compliance, duplex ultrasound, failed conservative treatment statement',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.029, I83.209',
   1, 'Prior auth required. 15 business day turnaround.',
   'Duplex must be within 6 months of procedure date or they will deny.',
   'https://www.bcbstx.com/provider/clinical/policies', '2025-01-01',
   'Similar to BCBS IL. Watch the 6-month ultrasound window.'],

  ['Blue Cross Blue Shield', 'Florida', 'Commercial',
   12, '12 weeks conservative therapy. Stockings 20-30 mmHg minimum. Must be worn daily.',
   0.5, null,
   'Duplex ultrasound showing reflux >0.5 sec. GSV diameter >4mm often cited in denial letters though not in official policy.',
   'C2 or higher',
   'Office notes, stocking compliance, duplex report, photos',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required.',
   'Florida BCBS often requests GSV diameter even when not in written policy. Document vessel size on every ultrasound.',
   '', '2025-01-01', ''],

  ['Blue Cross Blue Shield', 'New Jersey', 'Commercial',
   12, '12 weeks conservative therapy with 20-30 mmHg compression stockings.',
   0.5, null,
   'Duplex showing reflux >0.5 sec. Must be from accredited lab.',
   'C2 or higher',
   'Office notes, stocking compliance, duplex, symptom diary recommended',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required.',
   'NJ BCBS can be slow on auth — submit 3-4 weeks ahead.',
   '', '2025-01-01', ''],

  ['Blue Cross Blue Shield', 'New York', 'Commercial',
   12, '12 weeks conservative therapy. 20-30 mmHg stockings. Daily wear documented.',
   0.5, null,
   'Duplex ultrasound >0.5 sec reflux in GSV or SSV.',
   'C2 or higher',
   'Office notes, stocking Rx and compliance, duplex report, clinical photos',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required for ablation.',
   'NY BCBS follows Empire BCBS guidelines. Peer-to-peer available if denied.',
   '', '2025-01-01', ''],

  ['Blue Cross Blue Shield', 'California', 'Commercial',
   12, '12 weeks conservative treatment with 20-30 mmHg compression stockings documented at each visit.',
   0.5, null,
   'Duplex ultrasound with reflux >0.5 seconds. GSV diameter >5mm sometimes required.',
   'C2 or higher',
   'Detailed office notes, stocking compliance, duplex, photos',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required. CA has specific appeal rights.',
   'California has strong appeal rights — always appeal denials. GSV >5mm sometimes required even though not in written policy.',
   '', '2025-01-01', ''],

  // Aetna
  ['Aetna', 'National', 'Commercial',
   12, '12 weeks of conservative treatment. Compression stockings 20-30 mmHg. Must have documented compliance.',
   0.5, null,
   'Duplex ultrasound showing reflux >0.5 sec at saphenofemoral junction (SFJ) or saphenopopliteal junction (SPJ). GSV diameter not specifically required but document anyway.',
   'C2 or higher',
   'Physician notes at minimum every 4 weeks during conservative period, stocking prescription, compliance documentation, duplex ultrasound report, symptom documentation (VAS pain score helpful)',
   '36475, 36476, 36478, 36479, 36482, 36483, 93971',
   'I83.009, I83.019, I83.029, I83.209, I83.219, I83.229, I87.2, I87.31',
   1, 'Prior auth required. Aetna uses Carecore/AIM for auth.',
   'Aetna uses AIM Specialty Health for prior auth — separate portal from Aetna main. VAS pain score documentation strengthens cases.',
   'https://www.aetna.com/cpb/medical/data/600_699/0680.html', '2025-01-01',
   'Aetna Clinical Policy Bulletin 0680. One of the more detailed policies. Conservative — stick to 12 weeks minimum.'],

  ['Aetna', 'National', 'Medicare Advantage',
   12, 'Follows Medicare LCD L33971. 12 weeks conservative therapy.',
   0.5, null,
   'Reflux >0.5 sec. Follows Noridian/CGS LCD depending on region.',
   'C2 or higher',
   'Same as Medicare requirements — see LCD L33971',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required even for Medicare Advantage.',
   'Medicare Advantage plans must cover what Medicare covers but CAN require prior auth. Always verify.',
   '', '2025-01-01', 'Follows Medicare LCD L33971'],

  // UnitedHealthcare
  ['UnitedHealthcare', 'National', 'Commercial',
   12, '12 weeks conservative therapy. Compression stockings 20-30 mmHg minimum. Must be documented at each clinical encounter.',
   0.5, null,
   'Duplex ultrasound demonstrating reflux >0.5 seconds. Must be performed by registered vascular technologist (RVT) or in accredited vascular lab.',
   'C2 or higher',
   'Complete office notes at each visit, compression stocking prescription AND refill records, compliance documentation, duplex from accredited lab, photographs of varicosities, symptom severity scale',
   '36475, 36476, 36478, 36479, 36482, 36483, 93971',
   'I83.009, I83.019, I83.029, I83.209, I83.219, I83.229',
   1, 'Prior auth required. UHC uses their own auth portal.',
   'UHC requires accredited vascular lab — ICAVL accreditation specifically. Non-accredited lab reports frequently denied. Very strict on documentation completeness.',
   'https://www.uhcprovider.com/content/dam/provider/docs/public/policies/comm-medical-drug/varicose-vein-treatment.pdf', '2025-01-01',
   'UHC is one of the strictest. ICAVL accreditation for ultrasound lab is essential. Budget extra time for appeals.'],

  ['UnitedHealthcare', 'National', 'Medicare Advantage',
   12, 'Follows Medicare LCD. 12 weeks conservative therapy.',
   0.5, null,
   'Per Medicare LCD L33971 requirements.',
   'C2 or higher',
   'Medicare documentation requirements apply. Prior auth still required.',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required for Medicare Advantage despite following Medicare coverage.',
   'UHC MA plans are particularly aggressive about prior auth. Never assume Medicare coverage = automatic approval.',
   '', '2025-01-01', ''],

  // Cigna
  ['Cigna', 'National', 'Commercial',
   12, '12 weeks conservative management with graduated compression stockings (20-30 mmHg). Compliance must be documented.',
   0.5, null,
   'Duplex ultrasound showing reflux >0.5 seconds. GSV diameter >4.5mm sometimes referenced in medical review.',
   'C2 or higher',
   'Office notes documenting symptoms and conservative treatment, stocking Rx and compliance, duplex report, clinical photos if skin changes present',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209, I87.2',
   1, 'Prior auth required via Cigna portal or Evicore.',
   'Cigna uses Evicore for specialty auth in some markets. Check which platform applies. GSV >4.5mm helpful to document.',
   'https://www.cigna.com/healthcare-professionals/coverage-and-claims/clinical-payment-and-reimbursement-policies', '2025-01-01',
   'Cigna policy relatively straightforward. Evicore used in many markets — know which applies.'],

  // Medicare
  ['Medicare (Noridian)', 'West/Pacific', 'Medicare',
   12, 'LCD L33971: Conservative therapy for minimum 12 weeks. Compression stockings 20-30 mmHg. Must document daily wear compliance.',
   0.5, null,
   'Duplex ultrasound demonstrating: GSV reflux >0.5 sec OR SSV reflux >0.5 sec. Diameter criteria not in LCD but document GSV >4mm.',
   'C2 or higher (CEAP)',
   'History and physical with symptom documentation, VAS or VCSS score, compression stocking Rx and refill, duplex ultrasound report with reflux times documented, ICD-10 code matching symptoms',
   '36475, 36476, 36478, 36479, 36482, 36483, 93971',
   'I83.009, I83.019, I83.029, I83.209, I83.219, I83.229, I87.2, I87.311, I87.312, I87.313',
   0, 'No prior auth for Medicare FFS — but must meet LCD criteria for coverage.',
   'No prior auth needed for Medicare FFS but ADR requests are common. Keep impeccable documentation. Reflux time must be explicitly documented in ultrasound report.',
   'https://www.cms.gov/medicare-coverage-database/view/lcd.aspx?LCDId=33971', '2025-01-01',
   'LCD L33971 is the governing document. Noridian jurisdiction covers western states.'],

  ['Medicare (CGS)', 'Midwest/South', 'Medicare',
   12, 'LCD L33971 same as Noridian. 12 weeks conservative therapy. Compression 20-30 mmHg.',
   0.5, null,
   'Duplex showing reflux >0.5 sec. CGS is strict about reflux time being explicitly stated in the report.',
   'C2 or higher',
   'Same as Medicare LCD L33971 — complete symptom documentation, stocking compliance, duplex report',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   0, 'No prior auth for Medicare FFS.',
   'CGS specifically looks for reflux duration in the ultrasound report. If the report just says "reflux present" without a time, expect denial.',
   'https://www.cgsmedicare.com/hhh/coverage/coverage_guidelines/lcd_l33971.html', '2025-01-01',
   'CGS jurisdiction: KY, OH (J15) and various southern states. Reflux time must be explicit.'],

  ['Medicare (Palmetto GBA)', 'Southeast', 'Medicare',
   12, 'LCD L33971. 12 weeks. 20-30 mmHg stockings.',
   0.5, null,
   'Reflux >0.5 sec. Palmetto follows LCD L33971 closely.',
   'C2 or higher',
   'Full LCD L33971 documentation requirements',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   0, 'No prior auth for Medicare FFS.',
   'Palmetto GBA jurisdiction covers southeast. ADR audit rates can be high — document everything.',
   '', '2025-01-01', 'Jurisdiction: NC, SC, VA, WV, GA, FL (J11)'],

  // Humana
  ['Humana', 'National', 'Commercial',
   12, '12 weeks conservative therapy. 20-30 mmHg compression stockings. Daily wear required and documented.',
   0.5, null,
   'Duplex ultrasound with reflux >0.5 seconds. GSV or SSV.',
   'C2 or higher',
   'Office notes, stocking compliance, duplex, symptom documentation',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required.',
   'Humana can be slow on auth. Submit 3-4 weeks in advance.',
   '', '2025-01-01', ''],

  ['Humana', 'National', 'Medicare Advantage',
   12, 'Follows Medicare LCD L33971.',
   0.5, null,
   'Reflux >0.5 sec per Medicare LCD.',
   'C2 or higher',
   'Medicare documentation requirements. Prior auth still needed.',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required even for MA plans.',
   'Humana MA plans require prior auth. Star ratings sometimes affect ease of auth.',
   '', '2025-01-01', ''],

  // Molina
  ['Molina Healthcare', 'National', 'Medicaid',
   8, 'Typically 8 weeks conservative therapy for Medicaid. Some states require less.',
   0.5, null,
   'Duplex showing reflux >0.5 sec.',
   'C3 or higher often required for Medicaid',
   'Office notes, conservative treatment documentation, duplex, referral from PCP often required',
   '36475, 36476, 36478, 36479',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required. Referral from PCP sometimes needed.',
   'Medicaid plans often require PCP referral. Coverage varies significantly by state. Verify state-specific Molina policy.',
   '', '2025-01-01', 'Coverage varies significantly by state. Always verify state-specific policy.'],

  // Anthem
  ['Anthem / Elevance', 'National', 'Commercial',
   12, '12 weeks conservative management. 20-30 mmHg compression stockings with documented compliance.',
   0.5, null,
   'Duplex ultrasound demonstrating reflux >0.5 seconds in GSV or SSV.',
   'C2 or higher',
   'Clinical notes documenting symptoms, conservative treatment compliance, duplex ultrasound, clinical photographs',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required. Anthem uses AIM Specialty Health in many markets.',
   'Anthem/Elevance uses AIM Specialty Health for prior auth in most markets. Separate portal. Get familiar with AIM criteria.',
   'https://www.anthem.com/provider/policies', '2025-01-01',
   'AIM Specialty Health portal for prior auth. Formerly known as Anthem, now Elevance Health.'],

  // Oxford/UHC NY
  ['Oxford Health Plans', 'New York', 'Commercial',
   12, '12 weeks conservative therapy. Oxford follows UHC guidelines as subsidiary.',
   0.5, null,
   'Duplex reflux >0.5 sec. ICAVL accredited lab preferred.',
   'C2 or higher',
   'UHC/Oxford standard documentation requirements',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required via UHC portal.',
   'Oxford is a UHC subsidiary — follows UHC clinical policies. ICAVL accreditation important.',
   '', '2025-01-01', 'Oxford is UHC subsidiary. NY-specific plan.'],

  // Empire BCBS
  ['Empire BlueCross BlueShield', 'New York', 'Commercial',
   12, '12 weeks conservative therapy. 20-30 mmHg compression stockings.',
   0.5, null,
   'Duplex showing reflux >0.5 sec.',
   'C2 or higher',
   'Office notes, stocking compliance, duplex, photos of varicosities',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required.',
   'Empire BCBS is the main BCBS plan in NY. Peer-to-peer available on appeal.',
   '', '2025-01-01', 'Primary BCBS plan in New York state.'],

  // Medicaid generic
  ['Medicaid', 'New York', 'Medicaid',
   8, 'NY Medicaid typically requires 8 weeks conservative therapy. Varies by managed care plan.',
   0.5, null,
   'Duplex showing reflux >0.5 sec. C3 or higher often required.',
   'C3 or higher',
   'Office notes, PCP referral, conservative treatment documentation, duplex',
   '36475, 36476, 36478, 36479',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required. PCP referral usually needed.',
   'NY Medicaid managed care plans (Fidelis, Healthfirst, MetroPlus etc.) each have own nuances. Verify per plan.',
   '', '2025-01-01', 'Managed care plans vary — Fidelis, Healthfirst, MetroPlus, WellCare all slightly different.'],

  ['Medicaid', 'California', 'Medicaid',
   8, 'Medi-Cal requires 8 weeks conservative therapy. Managed care plans may vary.',
   0.5, null,
   'Duplex reflux >0.5 sec.',
   'C3 or higher',
   'Office notes, referral, conservative treatment, duplex',
   '36475, 36476, 36478, 36479',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required.',
   'Medi-Cal managed care — LA Care, Health Net, Molina CA each differ. Verify plan-specific.',
   '', '2025-01-01', ''],

  // Tricare
  ['TRICARE', 'National', 'Government',
   12, '12 weeks conservative therapy. Follows civilian Medicare-like guidelines.',
   0.5, null,
   'Duplex showing reflux >0.5 sec.',
   'C2 or higher',
   'Office notes, conservative therapy, duplex, active duty vs. retired status affects coverage',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required. Must use TRICARE-authorized provider.',
   'Must be TRICARE-authorized provider. Active duty vs. retired/dependent affects process.',
   '', '2025-01-01', 'Military insurance. Provider must be TRICARE-authorized.'],

  // WellCare
  ['WellCare', 'National', 'Medicare Advantage',
   12, 'Follows Medicare LCD L33971. 12 weeks conservative therapy.',
   0.5, null,
   'Duplex reflux >0.5 sec per LCD.',
   'C2 or higher',
   'Medicare LCD documentation requirements plus prior auth paperwork.',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required.',
   'WellCare MA — prior auth always required. Can be slow to process.',
   '', '2025-01-01', ''],

  // Highmark
  ['Highmark BCBS', 'Pennsylvania', 'Commercial',
   12, '12 weeks conservative therapy. 20-30 mmHg stockings.',
   0.5, null,
   'Duplex reflux >0.5 sec.',
   'C2 or higher',
   'Office notes, stocking compliance, duplex, photos',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required.',
   'PA-specific BCBS affiliate. Follows BCBS standard vein policy.',
   '', '2025-01-01', 'BCBS affiliate covering Pennsylvania, West Virginia, Delaware.'],

  // Health Net
  ['Health Net', 'California', 'Commercial',
   12, '12 weeks conservative therapy with documented compression stocking use.',
   0.5, null,
   'Duplex reflux >0.5 sec.',
   'C2 or higher',
   'Office notes, stocking compliance, duplex, photos',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   1, 'Prior auth required.',
   'CA-based plan. Centene subsidiary.',
   '', '2025-01-01', 'California plan, part of Centene.'],

  // Multiplan/PHCS
  ['MultiPlan / PHCS', 'National', 'Commercial',
   12, 'Follows contracted payer guidelines. Conservative therapy typically 12 weeks.',
   0.5, null,
   'Duplex reflux >0.5 sec.',
   'C2 or higher',
   'Standard documentation — follows underlying payer policy',
   '36475, 36476, 36478, 36479, 36482, 36483',
   'I83.009, I83.019, I83.209',
   0, 'Prior auth varies by contracted payer.',
   'MultiPlan is a network — actual payer determines coverage. Verify the underlying insurance carrier.',
   '', '2025-01-01', 'Network — not a direct payer. Verify underlying carrier.'],
];

policies.forEach(p => { try { ins.run(...p); } catch(e) {} });

module.exports = db;
