const Database = require('better-sqlite3');
const path = require('path');
const fs = require('fs');

const dbPath = process.env.DB_PATH || path.join(__dirname, 'data', 'radar.db');
fs.mkdirSync(path.dirname(dbPath), { recursive: true });
const db = new Database(dbPath);

db.exec(`
  CREATE TABLE IF NOT EXISTS restaurants (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    neighborhood TEXT,
    cuisine TEXT,
    platform TEXT,
    booking_url TEXT,
    days_advance INTEGER,
    advance_notes TEXT,
    gluten_free INTEGER DEFAULT 0,
    gf_notes TEXT,
    my_notes TEXT,
    price_range TEXT,
    hot_level INTEGER DEFAULT 2,
    archived INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS watchlist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    restaurant_id INTEGER NOT NULL,
    target_date TEXT NOT NULL,
    party_size INTEGER DEFAULT 2,
    notes TEXT,
    status TEXT DEFAULT 'watching',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
  );
`);

// Seed restaurant data
const ins = db.prepare(`INSERT OR IGNORE INTO restaurants
  (name, neighborhood, cuisine, platform, booking_url, days_advance, advance_notes, gluten_free, gf_notes, price_range, hot_level)
  VALUES (?,?,?,?,?,?,?,?,?,?,?)`);

// Add UNIQUE constraint support via INSERT OR IGNORE
try { db.exec('CREATE UNIQUE INDEX IF NOT EXISTS idx_restaurant_name ON restaurants(name)'); } catch(e) {}

const restaurants = [
  // 🔥🔥🔥 Hardest to get
  ['Carbone','Greenwich Village','Italian-American','Resy','https://resy.com/cities/ny/carbone',30,'Opens exactly at midnight 30 days out — set an alarm. Goes within seconds.',0,'Limited GF options, kitchen can accommodate but pasta is the focus','$$$$$',3],
  ['Don Angie','West Village','Italian-American','Resy','https://resy.com/cities/ny/don-angie',30,'Opens midnight 30 days out. Extremely competitive — refreshing at midnight is the move.',1,'Good GF options, kitchen is accommodating','$$$$$',3],
  ['Lilia','Williamsburg','Italian','Resy','https://resy.com/cities/ny/lilia',14,'Drops Mondays at noon for the following 2 weeks. Refreshing all day Monday.',0,'Pasta-forward but has some GF options — worth calling ahead','$$$$',3],
  ['Torrisi','NoLita','Italian-American','Resy','https://resy.com/cities/ny/torrisi',30,'Opens midnight 30 days out. One of the toughest in the city.',0,'Limited accommodations — not ideal for strict GF','$$$$$',3],
  ["Rao's",'East Harlem','Italian-American','Phone','',0,'Effectively invite-only. Tables are owned by regulars. Worth trying anyway.',0,'Traditional red sauce — very limited GF','$$$$$',3],
  ['Le Bernardin','Midtown','French Seafood','OpenTable','https://www.opentable.com/le-bernardin',30,'Easier than most 3-stars. Check 30 days out. Bar seats easier.',1,'Excellent GF accommodations — seafood-forward menu, kitchen is meticulous','$$$$$',3],
  ['Atomix','Gramercy','Korean Fine Dining','Tock','https://www.exploretock.com/atomix',60,'Prepaid tickets release ~60 days out. Set a Tock alert.',1,'Tasting menu kitchen accommodates GF well — notify when booking','$$$$$',3],
  ['Polo Bar','Midtown','American','Resy','https://resy.com/cities/ny/polo-bar',30,'Opens midnight 30 days out. Scene-y and very tough.',1,'Classic American menu, kitchen accommodates GF','$$$$$',3],
  ['Jua','Flatiron','Korean','Resy','https://resy.com/cities/ny/jua',30,'Opens midnight 30 days out. Tiny restaurant, insanely hard.',1,'Tasting menu, kitchen accommodates GF — notify in advance','$$$$$',3],
  ['Masa','Columbus Circle','Japanese Omakase','Phone','',60,'Call 60+ days out. $1000+/person. Most expensive restaurant in the US.',1,'Omakase — mostly fish/rice, naturally GF','$$$$$',3],
  ['Per Se','Columbus Circle','French-American','Tock','https://www.exploretock.com/perse',60,'Prepaid Tock tickets ~60 days out.',1,'Tasting menu, kitchen accommodates GF with advance notice','$$$$$',3],
  ['Eleven Madison Park','Flatiron','Vegan Fine Dining','Tock','https://www.exploretock.com/elevenmadisonpark',60,'Prepaid Tock tickets ~60 days out. Fully plant-based.',1,'Naturally very GF-friendly — plant-based kitchen','$$$$$',3],
  ['The Chef\'s Table at Brooklyn Fare','Midtown','French-Japanese','Phone','',90,'Call months out. Counter-only, extremely exclusive.',1,'Tasting menu, accommodates GF with notice','$$$$$',3],
  ['Gabriel Kreuther','Midtown','Alsatian','Resy','https://resy.com/cities/ny/gabriel-kreuther',30,'Opens midnight 30 days out. Michelin 2-star.',1,'Excellent GF — highly trained kitchen','$$$$$',3],
  ['Crown Shy','Financial District','American','Resy','https://resy.com/cities/ny/crown-shy',30,'Opens midnight 30 days out. Chef James Kent.',1,'GF accommodating — notify when booking','$$$$',3],
  ['Gotham','Greenwich Village','American','Resy','https://resy.com/cities/ny/gotham-restaurant',21,'Opens 3 weeks out. NYC institution.',1,'Excellent GF — classic NYC fine dining','$$$$',3],
  ['Tatiana','Lincoln Center','Caribbean-American','Resy','https://resy.com/cities/ny/tatiana-by-kwame-onwuachi',30,'Chef Kwame\'s flagship. Opens midnight 30 days out.',1,'Very GF friendly — Caribbean cuisine naturally GF','$$$$',3],
  ['Saga','Financial District','American Fine Dining','Resy','https://resy.com/cities/ny/saga',30,'63rd floor views. Opens midnight 30 days out.',1,'Tasting menu, accommodates GF','$$$$$',3],
  ['The NoMad Bar','Flatiron','American','Resy','https://resy.com/cities/ny/the-nomad-bar',30,'Opens midnight 30 days out.',1,'Very GF accommodating','$$$$$',3],
  ['Nusara','West Village','Thai','Resy','https://resy.com/cities/ny/nusara',21,'3 weeks out. Michelin-starred Thai.',1,'Thai cuisine naturally very GF-friendly','$$$$',3],
  ['Semma','Greenwich Village','South Indian','Resy','https://resy.com/cities/ny/semma',21,'3 weeks out. Michelin-starred South Indian.',1,'South Indian naturally GF — rice, lentils, no wheat','$$$',3],
  ['Rezdôra','Flatiron','Northern Italian','Resy','https://resy.com/cities/ny/rezdora',21,'3 weeks out. Michelin-starred Emilian pasta.',0,'Pasta-focused — not ideal for GF','$$$$',3],
  ['Oiji Mi','Flatiron','Korean Fine Dining','Resy','https://resy.com/cities/ny/oiji-mi',30,'Opens midnight 30 days out. Michelin-starred Korean.',1,'GF accommodating — Korean kitchen very aware','$$$$',3],
  ['Aska','Williamsburg','Nordic Fine Dining','Tock','https://www.exploretock.com/aska',30,'Prepaid tickets on Tock. Michelin 2-star Nordic.',1,'Nordic tasting menu — naturally GF-friendly','$$$$$',3],
  ['Atera','Tribeca','Nordic-American','Tock','https://www.exploretock.com/atera',30,'Prepaid Tock tickets. Intimate counter dining.',1,'Tasting menu kitchen accommodates GF','$$$$$',3],
  ['Nakazawa','Greenwich Village','Japanese Omakase','Resy','https://resy.com/cities/ny/sushi-nakazawa',30,'Opens midnight 30 days out. Featured in Jiro Dreams of Sushi.',1,'Naturally GF — fish/rice omakase','$$$$$',3],
  ['Sushi Noz','Upper East Side','Japanese Omakase','Resy','https://resy.com/cities/ny/sushi-noz',60,'Book 60 days out. One of NYC\'s best omakase.',1,'Omakase — fish/rice, naturally GF','$$$$$',3],
  ['Jungsik','Tribeca','Korean Fine Dining','OpenTable','https://www.opentable.com/jungsik',30,'30 days out. Michelin 2-star Korean.',1,'GF accommodating — Korean fine dining kitchen','$$$$$',3],
  ['Noda','Midtown','Japanese Fine Dining','OpenTable','https://www.opentable.com/noda-nyc',30,'30 days out. Michelin 2-star Japanese.',1,'Japanese fine dining — GF accommodating','$$$$$',3],
  ['Le Pavillon','Midtown','French Vegetable','Resy','https://resy.com/cities/ny/le-pavillon',30,'Opens midnight 30 days out. Daniel Humm spin-off.',1,'Naturally GF-friendly — vegetable tasting menu','$$$$$',3],
  ['Nakaji','Tribeca','Japanese Omakase','Phone','',60,'Call 60 days out. Extraordinary omakase.',1,'Naturally GF — fish/rice','$$$$$',3],
  ['Ichimura','Tribeca','Japanese Omakase','Phone','',60,'Very hard to get. Call months in advance.',1,'Naturally GF — omakase','$$$$$',3],
  ['Soto','Greenwich Village','Japanese','Resy','https://resy.com/cities/ny/soto',30,'Opens midnight 30 days out. Michelin starred.',1,'Very GF friendly — Japanese cuisine','$$$$',3],

  // 🔥🔥 Hard but possible
  ['Gramercy Tavern','Flatiron','American','Resy','https://resy.com/cities/ny/gramercy-tavern',28,'Opens ~28 days out. Tavern room (walk-in) is easier.',1,'One of the best GF-friendly fine dining spots in NYC','$$$$',2],
  ['Estela','NoLita','Mediterranean','Resy','https://resy.com/cities/ny/estela',21,'Releases weekly. Check Sundays.',1,'Very GF friendly — many naturally GF dishes','$$$$',2],
  ['Cote','Flatiron','Korean BBQ','Resy','https://resy.com/cities/ny/cote',21,'Releases weekly, check Monday mornings.',1,'Very GF friendly — KBBQ is naturally GF','$$$$',2],
  ['Frenchette','TriBeCa','French','Resy','https://resy.com/cities/ny/frenchette',21,'Opens 3 weeks out.',1,'Good GF options, staff aware and accommodating','$$$$',2],
  ['Le Coucou','SoHo','French','Resy','https://resy.com/cities/ny/le-coucou',30,'Opens midnight 30 days out.',1,'French cuisine accommodates GF well','$$$$$',2],
  ['Dirt Candy','Lower East Side','Vegetarian','Tock','https://www.exploretock.com/dirtcandy',30,'Prepaid tickets ~30 days out on Tock.',1,'Excellent GF options — creative vegetarian kitchen','$$$$',2],
  ['Oxomoco','Greenpoint','Mexican','Resy','https://resy.com/cities/ny/oxomoco',14,'Releases 2 weeks out.',1,'Very GF friendly — wood-fired Mexican','$$$',2],
  ['Scarpetta','Chelsea','Italian','OpenTable','https://www.opentable.com/scarpetta-restaurant-new-york',21,'OpenTable, 3 weeks out.',0,'Pasta-focused but kitchen can accommodate GF','$$$$',2],
  ['Momofuku Ko','East Village','American','Resy','https://resy.com/cities/ny/ko',7,'Counter seating only, drops daily at midnight.',1,'Kitchen accommodates GF — must notify when booking','$$$$$',2],
  ['Via Carota','West Village','Italian','Walk-in','',0,'No reservations. Arrive at opening (5:30pm) or go late.',1,'Many naturally GF Italian dishes','$$$',2],
  ['Lucali','Carroll Gardens','Pizza','Phone/Walk-in','',0,'Call at 5pm. First come first served. Bring wine.',0,'Pizza = not GF. But they are the best.','$$$',2],
  ['The Grill','Midtown','American Steakhouse','Resy','https://resy.com/cities/ny/the-grill-nyc',30,'Opens midnight 30 days out. Stunning Seagram Building.',1,'Classic steakhouse — very GF friendly','$$$$$',2],
  ['The Pool','Midtown','Seafood','Resy','https://resy.com/cities/ny/the-pool-nyc',30,'Sister to The Grill. Opens midnight 30 days out.',1,'Seafood-forward, naturally GF-friendly','$$$$$',2],
  ['The Modern','Midtown/MoMA','French-American','OpenTable','https://www.opentable.com/the-modern',21,'3 weeks out. Inside MoMA.',1,'Fine dining kitchen very GF accommodating','$$$$$',2],
  ['Nobu','Tribeca','Japanese-Peruvian','OpenTable','https://www.opentable.com/nobu-new-york',21,'3 weeks out. Still impossible on weekends.',1,'Very GF friendly — sashimi, black cod, naturally GF dishes','$$$$$',2],
  ['Daniel','Upper East Side','French','OpenTable','https://www.opentable.com/daniel',30,'Opens 30 days out. Michelin 2-star.',1,'Excellent GF — highly trained kitchen','$$$$$',2],
  ['Aquavit','Midtown','Scandinavian','OpenTable','https://www.opentable.com/aquavit',21,'3 weeks out. Michelin 2-star.',1,'Very GF friendly — Scandinavian cuisine accommodating','$$$$$',2],
  ['Marea','Columbus Circle','Italian Seafood','OpenTable','https://www.opentable.com/marea',21,'3 weeks out. Michael White\'s seafood pasta temple.',0,'Pasta-focused — seafood dishes GF safe','$$$$$',2],
  ['Ci Siamo','Hudson Yards','Italian','Resy','https://resy.com/cities/ny/ci-siamo',21,'3 weeks out.',1,'Good GF options — wood-fired kitchen','$$$$',2],
  ['Koloman','Flatiron','Austrian-French','Resy','https://resy.com/cities/ny/koloman',21,'3 weeks out. Elegant hotel restaurant.',1,'GF accommodating — European trained kitchen','$$$$',2],
  ['Le Jardinier','Midtown','French Vegetable','Resy','https://resy.com/cities/ny/le-jardinier-new-york',21,'3 weeks out. Michelin star, vegetable-forward.',1,'Excellent GF — vegetable-forward, naturally accommodating','$$$$',2],
  ["L'Artusi",'West Village','Italian','Resy','https://resy.com/cities/ny/l-artusi',21,'3 weeks out. West Village staple.',0,'Italian pasta-forward, some GF options','$$$',2],
  ['Benno','Gramercy','Mediterranean','Resy','https://resy.com/cities/ny/benno',21,'3 weeks out.',1,'Excellent GF accommodations','$$$$',2],
  ['Bâtard','Tribeca','European','OpenTable','https://www.opentable.com/batard-restaurant-tribeca',21,'3 weeks out. Michelin-starred TriBeCa gem.',1,'GF accommodating — European trained kitchen','$$$$',2],
  ['Café Boulud','Upper East Side','French','OpenTable','https://www.opentable.com/cafe-boulud-new-york',14,'2 weeks out.',1,'Very GF accommodating — Boulud kitchens known for dietary needs','$$$$',2],
  ['Carne Mare','Financial District','Steakhouse','Resy','https://resy.com/cities/ny/carne-mare',21,'3 weeks out.',1,'Steakhouse — naturally GF-friendly','$$$$',2],
  ["Zou Zou's",'Hudson Yards','Middle Eastern','Resy','https://resy.com/cities/ny/zou-zous',14,'2 weeks out.',1,'Middle Eastern naturally very GF-friendly','$$$',2],
  ['Bar Boulud','Upper West Side','French Bistro','OpenTable','https://www.opentable.com/bar-boulud',14,'2 weeks out.',1,'Boulud kitchen — very GF accommodating','$$$',2],
  ['Charlie Bird','SoHo','Italian-American','Resy','https://resy.com/cities/ny/charlie-bird',14,'2 weeks out.',1,'Good GF options, accommodating kitchen','$$$',2],
  ['Lure Fishbar','SoHo','Seafood','OpenTable','https://www.opentable.com/lure-fishbar',14,'2 weeks out.',1,'Seafood-forward, naturally GF-friendly','$$$',2],
  ['Dhamaka','Lower East Side','Indian','Resy','https://resy.com/cities/ny/dhamaka',14,'2 weeks out. Regional Indian.',1,'Indian cuisine naturally GF-friendly','$$',2],
  ['Hearth','East Village','American-Italian','Resy','https://resy.com/cities/ny/hearth-nyc',14,'2 weeks out.',1,'GF friendly — known for accommodating dietary needs','$$$',2],
  ['Barbuto','West Village','Italian','Resy','https://resy.com/cities/ny/barbuto',14,'2 weeks out. Jonathan Waxman\'s legendary roast chicken.',1,'Very GF accommodating — simple, elegant Italian','$$$',2],
  ['Cafe Altro Paradiso','SoHo','Italian','Resy','https://resy.com/cities/ny/cafe-altro-paradiso',14,'2 weeks out.',1,'GF accommodating — light Italian cuisine','$$$',2],
  ['Cookshop','Chelsea','American','OpenTable','https://www.opentable.com/cookshop',14,'2 weeks out.',1,'Very GF accommodating — farm-to-table American','$$$',2],
  ['Minetta Tavern','Greenwich Village','French Bistro','Resy','https://resy.com/cities/ny/minetta-tavern',30,'Opens midnight 30 days out. Black label burger is legendary.',1,'Good GF options — steak/fish dishes safe','$$$$',2],
  ['Balthazar','SoHo','French Brasserie','Resy','https://resy.com/cities/ny/balthazar',14,'2 weeks out. NYC institution.',1,'GF accommodating — French brasserie','$$$',2],
  ["Raoul's",'SoHo','French Bistro','Walk-in','',0,'No reservations. Show up and wait at the bar.',1,'French bistro — steak, fish, salads all GF safe','$$$',2],
  ['Loring Place','Greenwich Village','American','Resy','https://resy.com/cities/ny/loring-place',14,'2 weeks out.',1,'Very GF accommodating — farm-to-table focused','$$$',2],
  ['Night + Market','West Village','Thai','Resy','https://resy.com/cities/ny/night-market-nyc',14,'2 weeks out. LA Thai legend\'s NYC outpost.',1,'Thai naturally GF-friendly','$$',2],
  ['Thai Diner','Nolita','Thai-American','Resy','https://resy.com/cities/ny/thai-diner',7,'1 week out.',1,'Thai-American, very GF friendly','$$',2],
  ['Greca','Midtown','Greek','OpenTable','https://www.opentable.com/greca-nyc',14,'2 weeks out.',1,'Greek cuisine naturally very GF-friendly','$$$',2],
  ['Estiatorio Milos','Midtown','Greek Seafood','OpenTable','https://www.opentable.com/estiatorio-milos',14,'2 weeks out. Pristine Greek seafood.',1,'Excellent GF — whole fish, Greek salads','$$$$$',2],
  ['Uncle Boons','Nolita','Thai','Resy','https://resy.com/cities/ny/uncle-boons',14,'2 weeks out.',1,'Thai naturally GF-friendly','$$',2],
  ['Houseman','Hudson Square','American','Resy','https://resy.com/cities/ny/houseman',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ['Tuome','East Village','American-Asian','Resy','https://resy.com/cities/ny/tuome',14,'2 weeks out.',1,'Very GF accommodating','$$$',2],
  ['Contra','Lower East Side','American Tasting Menu','Resy','https://resy.com/cities/ny/contra',21,'3 weeks out.',1,'Accommodates GF — notify when booking','$$$',2],
  ['The Dutch','SoHo','American','Resy','https://resy.com/cities/ny/the-dutch',14,'2 weeks out.',1,'Very GF accommodating — American brasserie','$$$',2],
  ['Locanda Verde','Tribeca','Italian','Resy','https://resy.com/cities/ny/locanda-verde',14,'2 weeks out. Andrew Carmellini\'s Italian.',1,'GF accommodating — Italian kitchen','$$$',2],
  ['Manhatta','Financial District','American','Resy','https://resy.com/cities/ny/manhatta',21,'3 weeks out. Stunning 60th floor views.',1,'Fine dining kitchen accommodates GF','$$$$',2],
  ['Pebble Bar','Midtown','American','Resy','https://resy.com/cities/ny/pebble-bar',21,'3 weeks out.',1,'GF accommodating','$$$',2],
  ['Casa Mono','Gramercy','Spanish Tapas','Resy','https://resy.com/cities/ny/casa-mono',14,'2 weeks out.',1,'Spanish tapas naturally GF — meat, fish, veggies','$$$',2],
  ['Llama San','West Village','Japanese-Peruvian','Resy','https://resy.com/cities/ny/llama-san',21,'3 weeks out.',1,'Very GF friendly — ceviche, fish, rice','$$$',2],
  ['Sant Ambroeus','Upper East Side','Italian Cafe','OpenTable','https://www.opentable.com/sant-ambroeus-west-village',14,'2 weeks out.',1,'GF accommodating — light Italian','$$$',2],
  ['Orsay','Upper East Side','French Brasserie','OpenTable','https://www.opentable.com/orsay-restaurant',14,'2 weeks out.',1,'French brasserie — steak, fish, salads GF','$$$',2],
  ['Le Bilboquet','Upper East Side','French','Resy','https://resy.com/cities/ny/le-bilboquet',14,'2 weeks out. Buzzy UES French bistro.',1,'French bistro — GF accommodating','$$$',2],
  ['Rotisserie Georgette','Upper East Side','French Rotisserie','OpenTable','https://www.opentable.com/rotisserie-georgette',14,'2 weeks out.',1,'Rotisserie — naturally GF, excellent','$$$',2],
  ['Sette Mezzo','Upper East Side','Italian','Walk-in','',0,'No reservations, cash only. UES legend.',1,'GF accommodating — light Italian','$$$$',2],
  ['Lusardi\'s','Upper East Side','Northern Italian','OpenTable','https://www.opentable.com/lusardis',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ["Paola's",'Upper East Side','Italian','OpenTable','https://www.opentable.com/paolas-restaurant',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ['Wildair','Lower East Side','Wine Bar','Walk-in','',0,'No reservations. Tiny natural wine bar.',1,'Small plates, GF accommodating','$$',2],
  ['Momofuku Ssäm Bar','Midtown','American-Korean','Resy','https://resy.com/cities/ny/momofuku-ssam-bar',14,'2 weeks out.',1,'GF accommodating — Korean-American','$$$',2],
  ['Veronika','Flatiron','European','Resy','https://resy.com/cities/ny/veronika',14,'2 weeks out. Inside Fotografiska museum.',1,'GF accommodating — European trained kitchen','$$$$',2],
  ['Legacy Records','Hudson Yards','American','Resy','https://resy.com/cities/ny/legacy-records',14,'2 weeks out.',1,'GF accommodating, farm-to-table American','$$$$',2],
  ['Dame','Greenwich Village','British Seafood','Walk-in','',0,'No reservations. Tiny and special.',1,'Seafood-focused, naturally GF-friendly','$$$',2],
  ['Maison Pickle','Upper West Side','French-American','OpenTable','https://www.opentable.com/maison-pickle',14,'2 weeks out. UWS neighborhood staple.',1,'GF accommodating — American brasserie','$$$',2],
  ['Candle 79','Upper East Side','Vegan','OpenTable','https://www.opentable.com/candle-79',14,'2 weeks out.',1,'Excellent GF — vegan kitchen very accommodating','$$$',2],
  ['Baar Baar','East Village','Modern Indian','OpenTable','https://www.opentable.com/baar-baar-east-village',7,'1 week out.',1,'Very GF friendly — Indian cuisine naturally GF','$$',2],
  ['Buvette','West Village','French Bistro','Walk-in','',0,'No reservations. Go early or late.',1,'French bistro — eggs, meats, salads GF safe','$$',2],
  ['Rosemary\'s','West Village','Italian','Resy','https://resy.com/cities/ny/rosemarys',14,'2 weeks out. Garden rooftop.',0,'Italian pasta-forward — ask about fish/meat options','$$$',2],
  ['Lola','Flatiron','American','Resy','https://resy.com/cities/ny/lola-taverna',14,'2 weeks out.',1,'GF accommodating, modern American menu','$$$',2],
  ['Scalini Fedeli','Tribeca','Italian','OpenTable','https://www.opentable.com/scalini-fedeli',14,'2 weeks out.',0,'Traditional Italian, some GF options','$$$$',2],
  ['Pasquale Jones','NoLita','Italian Pizza','Resy','https://resy.com/cities/ny/pasquale-jones',14,'2 weeks out.',0,'Pizza-focused — not GF','$$$',2],
  ['Claudette','Greenwich Village','French-Provencal','Resy','https://resy.com/cities/ny/claudette',14,'2 weeks out.',1,'French-Provencal — GF accommodating','$$$',2],
  ['Casa La Femme','Greenwich Village','Egyptian','Resy','https://resy.com/cities/ny/casa-la-femme',14,'2 weeks out. Egyptian cuisine — romantic and unique.',1,'Middle Eastern/Egyptian naturally GF','$$$',2],
  ['King','West Village','French-Italian','Resy','https://resy.com/cities/ny/king-restaurant',14,'2 weeks out.',1,'GF accommodating — European kitchen','$$$',2],
  ['Boucherie','West Village','French Brasserie','Resy','https://resy.com/cities/ny/boucherie-west-village',14,'2 weeks out.',1,'French brasserie — steak, fish, GF friendly','$$$',2],
  ['Waverly Inn','West Village','American','Resy','https://resy.com/cities/ny/waverly-inn',21,'3 weeks out. NYC celebrity favorite.',1,'GF accommodating — American comfort food','$$$',2],
  ['Fedora','West Village','American','Resy','https://resy.com/cities/ny/fedora',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ['Mary\'s Fish Camp','West Village','Seafood','Walk-in','',0,'No reservations. Cash only. Best lobster roll.',1,'Seafood — naturally GF','$$',2],
  ['Pearl Oyster Bar','West Village','Seafood','Walk-in','',0,'No reservations. Legendary lobster roll.',1,'Seafood naturally GF','$$',2],
  ['The Musket Room','Nolita','New Zealand','Resy','https://resy.com/cities/ny/the-musket-room',21,'3 weeks out. Michelin-starred NZ cuisine.',1,'Excellent GF — tasting menu kitchen trained','$$$$',2],
  ['Peasant','Nolita','Italian','Resy','https://resy.com/cities/ny/peasant',14,'2 weeks out.',1,'GF accommodating — rustic Italian','$$$',2],
  ["Emilio's Ballato",'Nolita','Italian-American','Walk-in','',0,'No reservations. Celebrity haunt. Walk in early.',1,'GF accommodating — classic Italian-American','$$$',2],
  ['Inocente','Nolita','Mexican','Resy','https://resy.com/cities/ny/inocente',14,'2 weeks out.',1,'Mexican naturally GF — corn-based','$$$',2],
  ['Olmsted','Prospect Heights','American','Resy','https://resy.com/cities/ny/olmsted',21,'3 weeks out. Michelin-starred Brooklyn gem.',1,'Excellent GF — kitchen very accommodating','$$$$',2],
  ['Chez Ma Tante','Greenpoint','Canadian-French','Resy','https://resy.com/cities/ny/chez-ma-tante',14,'2 weeks out.',1,'GF accommodating — French Canadian kitchen','$$$',2],
  ['Claro','Gowanus','Mexican','Resy','https://resy.com/cities/ny/claro-brooklyn',14,'2 weeks out. Michelin-starred Oaxacan.',1,'Oaxacan naturally GF — corn masa, mole','$$$',2],
  ['Meadowsweet','Williamsburg','American','Resy','https://resy.com/cities/ny/meadowsweet',14,'2 weeks out. Michelin-starred.',1,'GF accommodating — farm-to-table','$$$',2],
  ['Celestine','Dumbo','Mediterranean','Resy','https://resy.com/cities/ny/celestine',14,'2 weeks out.',1,'Mediterranean naturally GF-friendly','$$$',2],
  ['Laser Wolf','Brooklyn','Israeli','Resy','https://resy.com/cities/ny/laser-wolf-brooklyn',14,'2 weeks out. Mike Solomonov\'s Israeli BBQ.',1,'Israeli/Middle Eastern naturally very GF-friendly','$$$',2],
  ['Misi','Williamsburg','Italian Pasta','Resy','https://resy.com/cities/ny/misi',21,'3 weeks out. Missy Robbins pasta temple.',0,'Pasta-focused — not GF','$$$',2],
  ['Keens Steakhouse','Midtown','Steakhouse','OpenTable','https://www.opentable.com/keens-steakhouse',14,'2 weeks out. NYC\'s oldest steakhouse.',1,'Classic steakhouse — naturally GF','$$$$',2],
  ['Smith & Wollensky','Midtown','Steakhouse','OpenTable','https://www.opentable.com/smith-and-wollensky',14,'2 weeks out. NYC steakhouse institution.',1,'Classic steakhouse — naturally GF','$$$$',2],
  ['Peter Luger','Williamsburg','Steakhouse','Walk-in','',0,'No OpenTable — call or walk in. Cash only. Legend.',1,'Pure steakhouse — naturally GF','$$$$',2],
  ['Gallaghers','Midtown','Steakhouse','OpenTable','https://www.opentable.com/gallaghers-steakhouse',14,'2 weeks out. Theater district since 1927.',1,'Classic steakhouse — GF friendly','$$$$',2],
  ['Porter House Bar and Grill','Columbus Circle','Steakhouse','OpenTable','https://www.opentable.com/porter-house-bar-and-grill',14,'2 weeks out.',1,'Steakhouse — naturally GF','$$$$',2],
  ['Quality Meats','Midtown','Steakhouse','OpenTable','https://www.opentable.com/quality-meats',14,'2 weeks out.',1,'Steakhouse — naturally GF friendly','$$$$',2],
  ['Ai Fiori','Midtown','Italian-French','OpenTable','https://www.opentable.com/ai-fiori',21,'3 weeks out.',1,'GF accommodating — fine dining kitchen','$$$$',2],
  ['Sushi Yasuda','Midtown','Japanese Omakase','OpenTable','https://www.opentable.com/sushi-yasuda',30,'30 days out. NYC omakase legend.',1,'Naturally GF — fish and rice only','$$$$$',2],
  ['Sushi Noz','Upper East Side','Japanese Omakase','Resy','https://resy.com/cities/ny/sushi-noz',60,'Book 60 days out.',1,'Naturally GF','$$$$$',3],
  ['Shuko','Greenwich Village','Japanese Omakase','Phone','',30,'Call 30 days out.',1,'Naturally GF — fish and rice','$$$$$',2],
  ['Cagen','East Village','Japanese Omakase','Phone','',30,'Call 30 days out. 8-seat omakase.',1,'Naturally GF — fish/rice','$$$$$',2],
  ['Sushi Amane','Midtown East','Japanese Omakase','Phone','',60,'Call 2 months out.',1,'Naturally GF — omakase','$$$$$',2],
  ['Sushi Seki','Upper East Side','Japanese Omakase','OpenTable','https://www.opentable.com/sushi-seki-uws',30,'30 days out. Late night omakase legend.',1,'Naturally GF','$$$$',2],
  ['Rebelle','Nolita','French','Resy','https://resy.com/cities/ny/rebelle',21,'3 weeks out.',1,'GF accommodating — fine dining French kitchen','$$$$',2],
  ['Theodora','Upper West Side','Greek','Resy','https://resy.com/cities/ny/theodora',14,'2 weeks out.',1,'Greek cuisine naturally GF-friendly','$$$',2],
  ['Sofreh','Prospect Heights','Persian','Resy','https://resy.com/cities/ny/sofreh',14,'2 weeks out.',1,'Persian cuisine naturally GF — rice dishes, stews','$$$',2],
  ['Wayan','Nolita','Indonesian','Resy','https://resy.com/cities/ny/wayan',14,'2 weeks out.',1,'Indonesian cuisine very GF-friendly','$$$',2],
  ['Nix','Greenwich Village','Vegetarian','Resy','https://resy.com/cities/ny/nix',14,'2 weeks out. Michelin-starred vegetarian.',1,'Excellent GF — vegetarian Michelin star','$$$',2],
  ['abcV','Flatiron','Vegetarian','OpenTable','https://www.opentable.com/abcv',14,'2 weeks out. Jean-Georges vegetarian.',1,'Excellent GF — plant-based kitchen','$$$',2],
  ['Employees Only','West Village','American','Walk-in','',0,'No reservations. Great late-night food and cocktails.',1,'GF accommodating — American small plates','$$$',2],
  ['Hundred Acres','SoHo','American','Resy','https://resy.com/cities/ny/hundred-acres',14,'2 weeks out.',1,'Very GF accommodating','$$$',2],
  ['Balaboosta','Nolita','Middle Eastern','Resy','https://resy.com/cities/ny/balaboosta',14,'2 weeks out.',1,'Middle Eastern naturally GF','$$$',2],
  ['Taboon','Hell\'s Kitchen','Middle Eastern','OpenTable','https://www.opentable.com/taboon',14,'2 weeks out.',1,'Middle Eastern — many GF options','$$$',2],
  ['Periyali','Flatiron','Greek','OpenTable','https://www.opentable.com/periyali',14,'2 weeks out.',1,'Greek naturally very GF-friendly','$$$',2],
  ['Ivan Ramen','Lower East Side','Japanese Ramen','OpenTable','https://www.opentable.com/ivan-ramen-slurp-shop',7,'1 week out.',1,'Rare ramen spot with actual GF options','$$',2],
  ['Seamore\'s','Nolita','Seafood','OpenTable','https://www.opentable.com/seamores-nolita',7,'1 week out.',1,'Seafood-focused, naturally GF-friendly','$$',2],
  ['Cecchi\'s','West Village','Italian','Resy','https://resy.com/cities/ny/cecchis',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ['Lodi','Rockefeller Center','Italian Cafe','Walk-in','',0,'No reservations.',1,'GF accommodating — light Italian','$$$',2],
  ['Osteria Morini','SoHo','Northern Italian','OpenTable','https://www.opentable.com/osteria-morini-soho',14,'2 weeks out.',0,'Pasta-focused — limited GF','$$$',2],
  ['Navy','SoHo','Seafood','Walk-in','',0,'No reservations.',1,'Seafood naturally GF-friendly','$$',2],
  ['Blanca','Bushwick','American Tasting Menu','Tock','https://www.exploretock.com/blanca',30,'Prepaid Tock. Michelin 2-star in Bushwick.',1,'Tasting menu accommodates GF','$$$$$',2],
  ['Quatorze Bis','Upper East Side','French Bistro','OpenTable','https://www.opentable.com/quatorze-bis',14,'2 weeks out.',1,'French bistro — steak, fish GF safe','$$$',2],
  ['Café Gitane','Nolita','French-Moroccan','Walk-in','',0,'No reservations. Always a line.',1,'GF accommodating — French-Moroccan small plates','$$',2],
  ['Joseph Leonard','West Village','American Bistro','Walk-in','',0,'No reservations. Small West Village gem.',1,'Accommodating kitchen, many GF options','$$$',2],
  ['Malaparte','West Village','Italian','Walk-in','',0,'No reservations.',1,'GF accommodating','$$$',2],

  // ✨ GF Focused / Gems
  ['Senza Gluten','West Village','Italian (100% GF)','OpenTable','https://www.opentable.com/senza-gluten',7,'100% gluten-free kitchen. Book 1-2 weeks out.',1,'100% dedicated gluten-free kitchen — total safe haven','$$$',1],
  ['Modern Bread and Bagel','Midtown West','Bakery/Cafe (100% GF)','Walk-in','',0,'No reservations needed. 100% GF bakery.',1,'100% dedicated GF facility — bagels, sandwiches, pastries','$',1],
  ['Shukette','Chelsea','Israeli/Mediterranean','Resy','https://resy.com/cities/ny/shukette',14,'Releases 2 weeks out.',1,'Very GF friendly — Israeli food naturally GF-forward','$$$',1],
  ['Superiority Burger','East Village','Vegetarian','Walk-in','',0,'No reservations — small counter spot.',1,'Many GF options clearly marked','$',1],
  ['Llama Inn','Williamsburg','Peruvian','Resy','https://resy.com/cities/ny/llama-inn',14,'2 weeks out.',1,'Peruvian naturally very GF-friendly — corn-based dishes','$$$',1],
  ['Hu Kitchen','Flatiron','100% GF/Paleo','Walk-in','',0,'No reservation. 100% GF and grain-free.',1,'100% dedicated GF facility','$$',1],
  ['Noglu','Upper East Side','100% GF French Bakery','Walk-in','',0,'No reservations. Paris import.',1,'100% dedicated GF bakery and cafe','$$',1],
  ['Risotteria Melotti','Greenwich Village','Italian Risotto','Resy','https://resy.com/cities/ny/risotteria-melotti',14,'2 weeks out. Risotto is naturally GF.',1,'GF-forward menu — risotto naturally GF','$$',1],
  ["Mimi Cheng's",'East Village','Taiwanese Dumplings','Walk-in','',0,'No reservations. GF dumpling options!',1,'GF dumpling options available — rare and wonderful','$$',1],
  ['Taïm','Multiple Locations','Israeli Falafel','Walk-in','',0,'Multiple locations. No reservations.',1,'Israeli — naturally GF falafel','$',1],
  ['The Little Beet','Multiple Locations','American GF','Walk-in','',0,'Fast casual, no reservations. GF-focused.',1,'GF-focused menu throughout','$$',1],
  ['Friedman\'s','Hell\'s Kitchen','American Diner','OpenTable','https://www.opentable.com/friedmans-restaurant-hells-kitchen',7,'1 week out. Known for GF-friendly menu.',1,'Extensive GF menu clearly marked','$$',1],
  ['Wild','Greenwich Village','American GF-focused','Resy','https://resy.com/cities/ny/wild-restaurant',14,'2 weeks out.',1,'Menu designed around dietary needs including GF','$$$',1],
  ['Naya','Midtown','Lebanese','OpenTable','https://www.opentable.com/naya-restaurant-midtown',7,'1 week out.',1,'Lebanese naturally GF','$$',1],
  ['Candle Cafe','Upper East Side','Vegan','OpenTable','https://www.opentable.com/candle-cafe-east',7,'1 week out.',1,'Vegan — excellent GF options','$$',1],
  ['Sunday in Brooklyn','Williamsburg','American Brunch','Resy','https://resy.com/cities/ny/sunday-in-brooklyn',7,'1 week out especially brunch.',1,'Very GF friendly — many GF options marked','$$$',1],
  ['Borealis','Upper East Side','Scandinavian','Resy','https://resy.com/cities/ny/borealis',14,'2 weeks out.',1,'Nordic cuisine very GF-friendly','$$$',1],
  ['Kopitiam','Lower East Side','Malaysian','Walk-in','',0,'No reservations. Tiny Malaysian spot.',1,'Rice-based — naturally GF','$',1],
  // Additional restaurants
  ['Sushi Gordon Ramsay','Midtown','Japanese','Resy','https://resy.com/cities/ny/lucky-cat-new-york',21,'3 weeks out.',1,'GF friendly — Japanese influenced','$$$$',3],
  ['Acquerello','Midtown','Italian Fine Dining','OpenTable','https://www.opentable.com/acquerello-nyc',21,'3 weeks out.',1,'GF accommodating','$$$$',3],
  ['Sushi Inoue','Midtown','Japanese Omakase','Phone','',60,'Call 60 days out.',1,'Naturally GF','$$$$$',3],
  ['Tempura Matsui','Midtown','Japanese Tempura','OpenTable','https://www.opentable.com/tempura-matsui',30,'30 days out. Michelin-starred tempura counter.',0,'Tempura = battered/gluten — not GF','$$$$$',3],
  ['Sushi Zo','Midtown','Japanese Omakase','Resy','https://resy.com/cities/ny/sushi-zo',30,'Opens 30 days out.',1,'Naturally GF — omakase fish/rice','$$$$$',3],
  ['Foul Witch','East Village','Italian','Resy','https://resy.com/cities/ny/foul-witch',14,'2 weeks out.',0,'Pasta-focused, limited GF','$$$',2],
  ['Quality Italian','Midtown','Italian Steakhouse','OpenTable','https://www.opentable.com/quality-italian',14,'2 weeks out.',1,'GF accommodating','$$$$',2],
  ['Bice','Midtown','Italian','OpenTable','https://www.opentable.com/bice-ristorante-nyc',14,'2 weeks out.',1,'GF accommodating','$$$$',2],
  ['Benjamin Steakhouse','Midtown','Steakhouse','OpenTable','https://www.opentable.com/benjamin-steakhouse',14,'2 weeks out.',1,'Steakhouse — naturally GF','$$$$',2],
  ['Ristorante Morini','Upper East Side','Italian','OpenTable','https://www.opentable.com/ristorante-morini',14,'2 weeks out.',0,'Pasta-focused — limited GF','$$$$',2],
  ['Sistina','Upper East Side','Italian','OpenTable','https://www.opentable.com/sistina-restaurant',14,'2 weeks out.',1,'GF accommodating','$$$$',2],
  ['Caravaggio','Upper East Side','Italian','OpenTable','https://www.opentable.com/caravaggio-restaurant',14,'2 weeks out.',1,'GF accommodating','$$$$',2],
  ['Nello','Upper East Side','Italian','Walk-in','',0,'Scene-y UES Italian. Walk in and hope.',0,'Pasta-focused — limited GF','$$$$$',2],
  ['Uva','Upper East Side','Italian Wine Bar','Walk-in','',0,'No reservations. Cozy UES wine bar.',1,'Small plates, GF accommodating','$$',2],
  ['Hotel Tortuga','Lower East Side','Mexican','Resy','https://resy.com/cities/ny/hotel-tortuga',14,'2 weeks out.',1,'Mexican naturally GF — corn tortillas','$$',2],
  ['Momofuku Noodle Bar','Midtown','Japanese-American','Resy','https://resy.com/cities/ny/momofuku-noodle-bar',14,'2 weeks out.',0,'Noodle-focused — limited GF','$$',2],
  ['Bar Veloce','Multiple Locations','Italian Wine Bar','Walk-in','',0,'No reservations.',1,'Small plates, GF accommodating','$$',2],
  ['Eataly','Flatiron','Italian Market','Walk-in','',0,'No reservations for most spots.',1,'Many GF options — ask at each counter','$$',2],
  ['Rubirosa','Nolita','Italian Pizza','Walk-in','',0,'No reservations. Best vodka pizza.',0,'Pizza — not GF','$$',2],
  ['Café Français','Financial District','French Cafe','Walk-in','',0,'No reservations.',1,'French cafe — eggs, salads, GF options','$$',2],
  ['Interlude','Flatiron','American','Resy','https://resy.com/cities/ny/interlude-nyc',21,'3 weeks out.',1,'Accommodates GF — notify when booking','$$$$',2],
  ['Le Fond','Bushwick','French','Resy','https://resy.com/cities/ny/le-fond',14,'2 weeks out.',1,'GF accommodating — French bistro','$$$',2],
  ['RedFarm','Upper West Side','Chinese-American','Resy','https://resy.com/cities/ny/redfarm-uws',14,'2 weeks out.',0,'Dim sum has gluten — limited GF','$$$',2],
  ['Oxbow Tavern','West Village','American','Resy','https://resy.com/cities/ny/oxbow-tavern',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ['Veronika','Flatiron','European','Resy','https://resy.com/cities/ny/veronika',14,'2 weeks out.',1,'GF accommodating','$$$$',2],
  ['LaLou','Prospect Heights','Wine Bar','Resy','https://resy.com/cities/ny/lalou',14,'2 weeks out.',1,'Small plates, GF accommodating','$$$',2],
  ["Jacob's Pickles",'Upper West Side','American Southern','OpenTable','https://www.opentable.com/jacobs-pickles',7,'1 week out.',0,'Biscuit-heavy — not ideal for GF','$$',2],
  ['Oxtail','Harlem','Caribbean','Resy','https://resy.com/cities/ny/oxtail-harlem',14,'2 weeks out.',1,'Caribbean naturally GF-friendly','$$$',2],
  ["Fiorentino's",'Gowanus','Italian-American','Walk-in','',0,'Cash only. Old school Brooklyn Italian.',0,'Traditional Italian — limited GF','$$',2],
  ['Sauvage','Greenpoint','French','Resy','https://resy.com/cities/ny/sauvage',14,'2 weeks out.',1,'GF accommodating — French bistro','$$$',2],
  ['Greenpoint Fish & Lobster','Greenpoint','Seafood','Walk-in','',0,'No reservations. Best fish tacos in Brooklyn.',1,'Seafood naturally GF — fish tacos on corn tortillas','$$',2],
  ["L'industrie",'Williamsburg','Pizza','Walk-in','',0,'No reservations. Best pizza in Brooklyn.',0,'Pizza — not GF, but legendary','$',2],
  ['Saraghina','Bed-Stuy','Italian','Walk-in','',0,'No reservations. Garden in back.',0,'Pizza-focused — not GF','$$',2],
  ['Prime Meats','Carroll Gardens','German-American','Walk-in','',0,'No reservations.',1,'GF accommodating — meat-focused','$$$',2],
  ['Gem Wine','Lower East Side','Wine Bar','Walk-in','',0,'No reservations. Tiny natural wine bar.',1,'Small plates, GF accommodating','$$',2],
  ["Harold's Meat + Three",'West Village','American Southern','Resy','https://resy.com/cities/ny/harolds-meat-three',14,'2 weeks out.',1,'Southern American — some GF options','$$$',2],
  ['The Jones','Greenwich Village','American','Resy','https://resy.com/cities/ny/the-jones-nyc',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ['Anfora','West Village','Italian Wine Bar','Walk-in','',0,'No reservations.',1,'Small plates, GF accommodating','$$',2],
  ['Lyaness','Lower East Side','American','Resy','https://resy.com/cities/ny/lyaness',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ['Bar Primi','East Village','Italian','Resy','https://resy.com/cities/ny/bar-primi',7,'1 week out.',0,'Pasta spot — limited GF','$$',2],
  ['Misipasta','Greenwich Village','Italian','Walk-in','',0,'No reservations. Fresh pasta focus.',0,'Pasta-focused — not GF','$$',2],
  ['Frankies 457','Carroll Gardens','Italian','Walk-in','',0,'No reservations. Garden in back. Cash vibes.',1,'Good GF options — salads, meat dishes','$$',2],
  ['Don Peppe','South Ozone Park','Italian-American','Phone','',0,'Call ahead. Cash only.',0,'Traditional Italian — limited GF','$$',2],
  ['The Four Horsemen','Williamsburg','Natural Wine Bar','Resy','https://resy.com/cities/ny/the-four-horsemen',14,'2 weeks out.',1,'Small plates, very GF accommodating','$$$',2],
  ['Ugly Baby','Carroll Gardens','Thai','Walk-in','',0,'No reservations. Seriously spicy Thai.',1,'Thai cuisine naturally very GF-friendly','$$',2],
  ['Mettā','Prospect Heights','American Wine Bar','Resy','https://resy.com/cities/ny/metta-brooklyn',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ['Runner & Stone','Gowanus','American Bakery','Walk-in','',0,'Walk-in. Great brunch.',0,'Bakery/bread-focused — not GF','$$',2],
  ['Westlight','Williamsburg','American Rooftop','Resy','https://resy.com/cities/ny/westlight',14,'2 weeks out.',1,'GF accommodating','$$$',2],
  ['Oxalis','Prospect Heights','French-American','Resy','https://resy.com/cities/ny/oxalis',14,'2 weeks out.',1,'GF accommodating — tasting menu kitchen','$$$$',2],
  ['Aldama','Williamsburg','Mexican','Resy','https://resy.com/cities/ny/aldama',14,'2 weeks out.',1,'Mexican naturally GF-friendly — corn-based','$$$',2],
  ['Keste Pizza & Vino','West Village','Neapolitan Pizza','Walk-in','',0,'No reservations. Best Neapolitan in NYC. Has GF pizza!',1,'They have a GF pizza option!','$$',2],
  ['Laut','Union Square','Malaysian-Thai','Resy','https://resy.com/cities/ny/laut',7,'1 week out.',1,'SE Asian naturally GF-friendly','$$',1],
  ['Zenon Taverna','Astoria','Greek','OpenTable','https://www.opentable.com/zenon-taverna',7,'1 week out.',1,'Greek naturally GF','$$',1],
  ['Qi Bangkok Eatery','Theater District','Thai','OpenTable','https://www.opentable.com/qi-bangkok-eatery',7,'1 week out.',1,'Thai naturally GF-friendly','$$',1],
];

restaurants.forEach(r => { try { ins.run(...r); } catch(e) {} });

module.exports = db;
